### ISSUE TITLE
Remove the helm installation for istio and use istioctl

### ISSUE THREAD

**Issue by Gsantomaggio** [Gsantomaggio/k8s#1]
Remove the helm installation for istio and use istioctl

**Comment by ghost** [comment]
I need a rabbitMQ server deployed on k8s cluster without istio service mesh first. Then I will deploy Istio service mesh on top to move traffic from outside into cluster using Istio ingress. And then handle that traffic and do multiple traffic engineering use cases like traffic shifting, fault tolerance, mirroring, etc. 

In later iterations, we will introduce other Istio functionality like mTLS, policies and monitoring.

**Comment by ghost** [comment]
by server I mean cluster. Single cluster first.

**Comment by Gsantomaggio** [comment]
the example now uses k8s service discovery, see https://github.com/Gsantomaggio/k8s/pull/2
you can run it without istio here: https://github.com/Gsantomaggio/k8s/tree/wip/rabbitmq_traffic#without-istio
